### ISSUE TITLE
Add deprecation warning in favour of "User level tasks" (new in vscode 1.42)

### ISSUE THREAD

**Issue by vyachkonovalov** [edonet/vscode-command-runner#15]
https://code.visualstudio.com/updates/v1_42#_user-level-tasks
https://go.microsoft.com/fwlink/?LinkId=733558

**Comment by mn4367** [comment]
I don't think VSCode Command Runner can be deprecated, especially with regard to keyboard shortcuts:

1. Binding a keyboard shortcut to a user level task and then using that shortcut will _always_ pop up the command palette showing the list of user tasks which is annoying since you have to select one of the tasks to run it. VSCode Command Runner instead executes the task immediately, which, I think, is what users usually expect from a keyboard shortcut.
2. With VSCode Command Runner you can chain VS Code builtin commands with your own command like:

    ```json
    {
        "key": "ctrl+s",
        "command": "command-runner.run",
        "args": { "command": "${command:workbench.action.files.save} compile-markdown.sh \"${file}\"",
        "when": "resourceLangId == markdown"
    },
    ```
@vyachkonovalov, do you know how to achieve that with user level tasks, especially with regard to problem 1.?

**Comment by vyachkonovalov** [comment]
@mn4367 Nope, you are right, can't find neither 1. nor 2. in tasks.json docs.
