### ISSUE TITLE
Make command output be available as a input variable

### ISSUE THREAD

**Issue by mwitkow** [edonet/vscode-command-runner#22]
I'm trying to run a shell command and use it's output (similar to bash `$(my_script.sh)` syntax) as a `command`-type input variable (`${input:<somevariable>}`) inside launch.json, see [here](https://code.visualstudio.com/docs/editor/variables-reference) for reference.

Having this would be super powerful as it allows one to script input variables (e.g. what binary file to debug) into `launch.json` and `task.json` entries.

However, it seems that the command runner executes the echo command in the shell, prints it out, but sets nothing as the return for the program.

For completeness, this is what I'm trying to do:
a bash script that given a `${relativeFile}` in view will find it's Bazel GUnit test runner. For simplicity, it is now an echo statement

.vscode/helpers/bazel_get_testrunner_binary_for_file.sh:
```
#!/bin/env bash
echo "bazel-out/k8-dbg/bin/lib/hello-greet/hello-greet_test"
```
settings.json contains:
```
        "command-runner.commands": {
            "bazel_get_testrunner_binary_for_file": "bash  ${workspaceFolder}/.vscode/helpers/bazel_get_testrunner_binary_for_file.sh ${relativeFile}",
        }
```

launch.json contains:
```
... 
{
            "name": "(gdb) Test file",
            "type": "cppdbg",
            "request": "launch",

            "externalConsole": false,
            "MIMode": "gdb",
            // These are the paths (after k8-dbg to the main you want to debug)
            "program": "${input:bazelstuff}",
            "cwd": "${workspaceFolder}/bazel-out/k8-dbg/bin/main/hello-world.runfiles/__main__",
        }
    ],
    "inputs": [
        {
        "type": "command",
        "command": "command-runner.run",
        "id": "bazelstuff",
        "args": { "command": "bazel_get_testrunner_binary_for_file" }
        },

    ]
```

The desired state would be for the `echo` command from the shell script to end up as `${input:bazelstuff}` variable. Apparently it is possible as this is what `"extension.mochaSupport.testPicker"` in the [example](https://code.visualstudio.com/docs/editor/variables-reference) does

**Comment by edonet** [comment]
Sorry, this extension uses the internal terminal to run commands, which will be an asynchronous expiration, and the terminal does not give the API to get the output content. We can't solve your problem for the time being. Maybe you can consider shell environment parameters. This issue is closed first. If you get a better solution, please let us know.

**Comment by AZMCode** [comment]
I can absolutely think of a way to do this.
Create our own FIFO.
While this would be a little closer to bare metal than a lot of other extensions, one could create a FIFO, run the command redirecting all output there, and piping the output to both the VSCode terminal and our own buffer we could output from the extension itself.

As long as we control the command's process async wouldn't matter, since the command callback is async as well, and we'd know when to return, which is when the command dies.

**Comment by AZMCode** [comment]
After a lot of fuzzing around I've found a solution that uses zero dependencies and that would work, were it not for the fact every single method of running an external command through Node's API returns an empty string. Perhaps it's something to do with permissions, but I'mma keep

**Comment by AZMCode** [comment]
Here's [my current progress](https://github.com/edonet/vscode-command-runner/pull/36).
